on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: R-CMD-check

jobs:
  pre_deploy:
    runs-on: ${{ matrix.config.os }}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      _R_CHECK_TESTS_NLINES_: 0
      NOT_CRAN: true
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
            r-version: ${{ matrix.config.r }}
            use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::covr
          needs: check, coverage

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
        
      # Needed?
      # - name: Downgrade pkgdown
      #   run: |
      #     remotes::install_version("pkgdown", "2.0.3")
      #   shell: Rscript {0}
        
      - name: Build docs
        run: |
          Rscript -e 'devtools::document(); pkgdown::build_site(new_process = FALSE)'
          touch docs/.nojekyll
      - uses: actions/upload-pages-artifact@v1
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          path: ./docs

  deploy:
    runs-on: ubuntu-latest
    needs: pre_deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/deploy-pages@v1